language: c

notifications:
  email: false

git:
  depth: 3
  
os:
  - linux
#  - osx # temp disable due to travis image problem
  
osx_image: xcode8.2  #xcode8.2 needed for CLOCK_MONOTONIC() in pisum.c  
dist: trusty

addons:
  apt:
    sources: 
        - ubuntu-toolchain-r-test
    packages: 
        - gfortran
        - libopenblas-dev

before_install:
    - if [[ $TRAVIS_OS_NAME == osx ]]; then
        brew update;
        brew install gcc;
        brew install gfortran;
        brew install homebrew/science/openblas;
        export FC=gfortran;
      else
        export FC=gfortran-5;
      fi

install: 
  - cd bin
  - cmake ..
  - make
   
script:    
  - ./kind

