language: python
group: travis_latest

git:
  depth: 3
  quiet: true

python:
- 3.6

env: FC=gfortran-6

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gfortran-6
    - libopenblas-dev
      
matrix:
  include:
  - os: linux
    python: 3.6
    install: pip install -e .[tests,cov]
    script: 
    - flake8
    - mypy . --ignore-missing-imports
    after_success:
    - pytest --cov --cov-config=setup.cfg
    - coveralls
    
  #- os: osx
  #  - brew update > /dev/null
  #   - brew install gcc || brew link --overwrite gcc > /dev/null
  #   - export FC=gfortran

install: pip install -e .[tests]

script: pytest -v

