language: c
group: travis_latest

git:
  depth: 3
  quiet: true

os:
- linux
- osx

env: FC=gfortran-6

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gfortran-6
      - libopenblas-dev

before_install:
- if [[ $TRAVIS_OS_NAME == osx ]]; then
  brew update > /dev/null;
  brew install gcc > /dev/null || brew link --overwrite gcc > /dev/null;
  brew install openblas opencoarrays;
  export FC=gfortran;
  fi

install:
- cd bin
- cmake ..
- cmake --build .

- pip install -e .[tests]

script:
- ctest -V
- cd ..

- pytest -rsv
- flake8
#- mypy . --ignore-missing-imports

after_success:
- if [[ $TRAVIS_PYTHON_VERSION == 3.6* ]]; then
  pytest --cov --cov-config=setup.cfg;
  coveralls;
  fi

