language: c

os:
  - linux
  - osx

osx_image: xcode9  
# xcode >= 8.2 needed for CLOCK_MONOTONIC() in pisum.c

env: FC=gfortran

dist: trusty
group: edge

notifications:
  email: false

git:
  depth: 3

addons:
  apt:
    packages:
      - gfortran
      - libopenblas-dev

before_install:
  - if [[ $TRAVIS_OS_NAME == osx ]]; then
      brew update;
      brew install gcc;
      brew link --overwrite gcc;
      brew install openblas;
      brew install opencoarrays;
    fi

install:
  - cd bin
  - cmake ..
  - make -k

script:
  - ./kind

