language: c
fast_finish: true

os:
  - linux
  - osx

osx_image: xcode9  
# xcode >= 8.2 needed for CLOCK_MONOTONIC() in pisum.c

env: FC=gfortran-6

group: travis_latest

git:
  depth: 3

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gfortran-6
      - libopenblas-dev

before_install:
  - if [[ $TRAVIS_OS_NAME == osx ]]; then
      brew update;
      brew install gcc || true;
      brew link --overwrite gcc;
      brew install openblas opencoarrays;
      export FC=gfortran;
    fi

install:
  - cd bin
  - cmake ..
  - make

script:
  - make test
  
on_failure:
  - ctest -V

