language: c

notifications:
  email: false

git:
  depth: 3
  
os:
  - linux
  
dist: trusty

addons:
  apt:
    sources: ['ubuntu-toolchain-r-test']
    packages: ['gfortran-5','libopenblas-dev']

env:
  - FC=gfortran-5

#    - os: osx 
#      osx_image: xcode8.2
#      compiler: gcc
#      env: 
#        - COMP=gfortran
#      before_install:
#        - brew update
#        - brew install gcc 
#        - brew install homebrew/science/openblas

install: 
  - cd bin
  - cmake ..
  - make VERBOSE=1
   
script:    
  - ./kind

