language: c

notifications:
  email: false

git:
  depth: 3

matrix:
  include:
    - os: linux
      sudo: true
      dist: trusty
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['gfortran-5','libopenblas-dev']
      env: 
        - COMP=gfortran-5

#    - os: osx 
#      osx_image: xcode8.2 # Needs at least El Capitan for clock_gettime()
#      compiler: gcc
#      env: 
#        - COMP=gfortran
#      before_install:
#        - brew update
#        - brew install gcc 
#        - brew install homebrew/science/openblas

script: 
    - cd bin
    - FC=$COMP cmake ..
    - make VERBOSE=1

