language: c

notifications:
  email: false

git:
  depth: 3

os:
  - linux
#  - osx # temp disable due to travis image problem

osx_image: xcode9  #xcode >= 8.2 needed for CLOCK_MONOTONIC() in pisum.c

dist: trusty
group: edge

addons:
  apt:
    sources:
        - ubuntu-toolchain-r-test
    packages:
        - gfortran-6
        - libopenblas-dev

before_install:
    - if [[ $TRAVIS_OS_NAME == osx ]]; then
        brew update;
        brew install gcc;
        brew install homebrew/science/openblas;
      else
        mkdir -p $HOME/.local/bin;
        ln -fs /usr/bin/gfortran-6 "$HOME/.local/bin/gfortran";
      fi

    - export PATH="$HOME/.local/bin:$PATH"
    - gfortran --version

install:
  - cd bin
  - cmake ..
  - make

script: ./kind

