language: c

notifications:
  email: false

git:
  depth: 3

os:
  - linux
#  - osx # temp disable due to travis image problem

env: FC=/usr/bin/gfortran-5

osx_image: xcode8.2  #xcode8.2 needed for CLOCK_MONOTONIC() in pisum.c
dist: trusty

addons:
  apt:
    sources:
        - ubuntu-toolchain-r-test
    packages:
        - gfortran-5
        - libopenblas-dev

before_install:
    - if [[ $TRAVIS_OS_NAME == osx ]]; then
        brew update;
        brew install gcc;
        brew install homebrew/science/openblas;
      else
        mkdir -p $HOME/.local/bin;
        ln -fs /usr/bin/gfortran-5 "$HOME/.local/bin/gfortran";
      fi

    - export PATH="$HOME/.local/bin:$PATH"
    - gfortran --version

install:
  - cd bin
  - cmake ..
  - make

script:
  - ./kind

