language: c

notifications:
  email: false

git:
  depth: 3
  
os:
  - linux
  - osx
  
dist: trusty

addons:
  apt:
    sources: ['ubuntu-toolchain-r-test']
    packages: ['gfortran-5','libopenblas-dev']

env:
  - FC=gfortran-5

before_install:
    - if [[ $TRAVIS_OS_NAME == osx ]]; then
        env: FC=gfortran;
        brew update;
        brew install gcc;
        brew install homebrew/science/openblas;
    fi

install: 
  - cd bin
  - cmake ..
  - make VERBOSE=1
   
script:    
  - ./kind

