language: python
group: travis_latest

git:
  depth: 3
  quiet: true

python:
- 2.7
- 3.6

os:
- linux

env: FC=gfortran-6

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gfortran-6
      - libopenblas-dev

before_install:
- if [[ $TRAVIS_OS_NAME == osx ]]; then
  brew update > /dev/null;
  brew install gcc > /dev/null || brew link --overwrite gcc > /dev/null;
  brew install openblas opencoarrays;
  export FC=gfortran;
  fi

install:
- pip install -e .[tests]
- if [[ $TRAVIS_PYTHON_VERSION == 3.6* ]]; then pip install -e .[cov]; fi

- cd bin
- cmake ..
- cmake --build .

script:
- ctest -V
- cd ..

- if [[ $TRAVIS_PYTHON_VERSION == 3.6* ]]; then
  flake8;
  mypy . --ignore-missing-imports;
  fi

after_success:
- if [[ $TRAVIS_PYTHON_VERSION == 3.6* ]]; then
  pytest --cov --cov-config=setup.cfg;
  coveralls;
  fi

