language: c

os:
  - linux
  - osx

osx_image: xcode9  
# xcode >= 8.2 needed for CLOCK_MONOTONIC() in pisum.c

env: FC=gfortran-6

dist: trusty
group: edge

notifications:
  email: false

git:
  depth: 3

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gfortran-6
      - libopenblas-dev

before_install:
    - if [[ $TRAVIS_OS_NAME == osx ]]; then
        brew update;
        brew install gcc;
        brew install homebrew/science/openblas; 
        export FC=gfortran;
      fi

install:
  - cd bin
  - cmake ..
  - make

script:
  - ./kind

