language: python
group: travis_latest
dist: xenial

git:
  depth: 25
  quiet: true

python:
- 3.7

env: FC=gfortran

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gfortran-6
    - libopenblas-dev

matrix:
  include:
  - os: linux
    env: FC=gfortran-6
    python: 3.6
    install: pip install -e .[tests,lint]
    script:
    - flake8
    - mypy .
    after_success:
    - pytest --cov
    - coveralls
  # - os: osx
    # language: sh
    # before_install:
    # - brew update > /dev/null
    # - brew install gcc > /dev/null
    # install: pip3 install -e .[tests]
#  - os: windows
#    language: sh
#    before_install:
#    - choco install python3
#    - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"

install: pip install -e .[tests]

script: pytest -r a -v

