image:
- Visual Studio 2017
- Ubuntu1804

stack: python 3.7

environment:
  PY_DIR: C:\Python37-x64

clone_depth: 25

build: off

init:
- cmd: set PATH=%PY_DIR%;%PY_DIR%\Scripts;%PATH%

install:
- pip install -e .[tests]
- cmake -B build

test_script:
- sh: cmake --build build --parallel --target test
- cmd: cmake --build build --target RUN_TESTS
- pytest -r a -v
